SELECT
	*
FROM
	DEPARTMENTS d ;

SELECT
	DEPARTMENT_NAME,
	MANAGER_ID
FROM
	DEPARTMENTS d ;
--1. EMPLOYEES 테이블의 EMPLOYEE_ID, LAST_NAME, EMAIL 컬럼 조회
SELECT
	EMPLOYEE_ID,
	LAST_NAME,
	EMAIL
FROM
	EMPLOYEES e ;
--2. EMPLOYEES 테이블의 JOB_ID 컬럼 조회
SELECT
	JOB_ID
FROM
	EMPLOYEES e ;
--3. JOBS 테이블의 JOB-TITLE, MIN_SALASRY, MAX_SALARY 컬럼 조회
SELECT
	JOB_TITLE,
	MIN_SALARY,
	MAX_SALARY
FROM
	JOBS j ;
--4. DEPARTMENTS 테이블의 모든 컬럼 조회
SELECT
	*
FROM
	DEPARTMENTS d ;

SELECT
	EMPLOYEE_ID,
	SALARY,
	SALARY * 12 AS "연봉"
FROM
	EMPLOYEES e ;
-- DISTINCT : 중복 제거
SELECT
	DISTINCT MANAGER_ID
FROM
	EMPLOYEES e ;
--1. EMPLOYEES 테이블에서 부서(DEPARTMENTS) 아이디 조회
-- 중복을 제거하여 조회하세요.
SELECT
	DISTINCT DEPARTMENT_ID
FROM
	EMPLOYEES e ;
--2. EMPLOYEES 테이블에서 월급(SALARY), 연봉, 연봉(보너스 포함) 조회
-- 산술 연산자를 사용하세요.
-- 보너스 컬럼은 COMMISION_PCT 입니다.
-- 연봉과 연봉(보너스포함)은 컬럼명에 별칭을 주세요.
-- 보너스 포함한 연봉 : (월급+보너스*월급)*12
SELECT
	SALARY,
	SALARY * 12 AS "연봉",
	(SALARY + COMMISSION_PCT * SALARY)* 12 AS "연봉(보너스 포함)"
FROM
	EMPLOYEES e;

SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE
	SALARY >= 10000;

SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME
FROM
	EMPLOYEES e
WHERE
	EMPLOYEE_ID < 150 ;

SELECT
	FIRST_NAME,
	LAST_NAME
FROM
	EMPLOYEES e
WHERE
	FIRST_NAME = 'Peter';
-- 같지 않다 : !=, ^=, <>

SELECT
	*
FROM
	EMPLOYEES e
WHERE
	HIRE_DATE > '2006-01-01';
--1. 직원 테이블에서 부서 번호가 90번인 직원들을 조회
-- 부서번호 컬럼명 : DEPARTMENT_ID
-- 조회할 컬럼 : FIRST_NAME, LAST_NAME, EMAIL
SELECT
	FIRST_NAME,
	LAST_NAME,
	EMAIL
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID = 90 ;
--2. 월급이 10,000 달러 이상인 직원들을 조회
-- 조회할 컬럼 : JOB_ID, MANAGER_ID, DEPARTMENT_ID
SELECT
	JOB_ID,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	SALARY >= 10000;
--3. 보너스를 포함한 연봉이 20,000 달러 이상인 직원들 조회
-- 조회할 컬럼 : EMPLOYEE_ID, FIRST_NAME, 연봉, HIRE_DATE
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	SALARY * 12 AS "연봉",
	HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	(SALARY + COMMISSION_PCT * SALARY)* 12 >= 20000;

--AND 연산
SELECT * FROM EMPLOYEES e 
WHERE MANAGER_ID = 100
AND DEPARTMENT_ID = 80
AND SALARY >= 12000;

--OR 연산
SELECT * FROM EMPLOYEES e 
WHERE SALARY >= 10000
OR DEPARTMENT_ID = 100;

--BETWEEN 연산 : 월급이 5000 이상, 10000 이하인 직원 조회
SELECT * FROM EMPLOYEES e 
WHERE SALARY BETWEEN 5000 AND 10000;

--NOT 연산 : 입사일이 2005년 ~ 2006년 사이인 직원 빼고 조회
SELECT * FROM EMPLOYEES e 
WHERE HIRE_DATE not BETWEEN '2005-01-01' AND '2006-01-01';

--LIKE 연산 : 표현식 %
SELECT * FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE 'N%';

-- first_name이 en으로 끝나는 데이터 조회
SELECT * FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE '%en';

-- first_name의 중간에 ar이 해당하는 데이터 조회
SELECT *FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE '%ar%';

--LIKE 연산 : 표현식 _
SELECT * FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE '_i';

SELECT * FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE 'P__';


--IS NULL 연산
SELECT * FROM EMPLOYEES e 
WHERE COMMISSION_PCT IS NULL;

--IN 연산 : department_id가 80 또는 100인 데이터 조회
SELECT * FROM EMPLOYEES e 
WHERE DEPARTMENT_ID IN('80', '100');

--연결 연산자 : 여러 개의 컬럼 값을 하나의 컬럼처럼 연결 시켜줄 수 있는 연산자
SELECT FIRST_NAME ||' '|| LAST_NAME  FROM EMPLOYEES e 





