SELECT * FROM EMPLOYEES e ;


UPDATE EMPLOYEES SET last_name = '김'
WHERE EMPLOYEE_ID = 207;

SELECT * FROM EMPLOYEES e ;


SELECT * FROM EMPLOYEES e ;
UPDATE EMPLOYEES SET EMAIL = 'Donald', PHONE_NUMBER = '01044445555', COMMISSION_PCT = 0.5
WHERE FIRST_NAME = 'Donald';

UPDATE EMPLOYEES SET HIRE_DATE = SYSDATE, SALARY = 15000
WHERE PHONE_NUMBER = '590.423.4567';