
SELECT * FROM ACCOUNTS ;
DELETE FROM ACCOUNTS ;
COMMIT;


CREATE SEQUENCE accounts_seq
INCREMENT BY 1 -- 1씩 증가
START WITH 1  -- 1부터 시작
MINVALUE 1 -- 최솟값 1
MAXVALUE 5 -- 최댓값 5
nocycle;

INSERT INTO accounts VALUES(accounts_seq.nextval, '이름', 10000);
SELECT * FROM ACCOUNTS ;

ALTER SEQUENCE accounts_seq MAXVALUE 99999;

SELECT * FROM EMPLOYEES e ;

DELETE FROM ACCOUNTS;

CREATE INDEX IDX_NAME ON ACCOUNTS(ACCOUNT_NAME);

INSERT INTO ACCOUNTS(ACCOUNT_ID, ACCOUNT_NAME, BALANCE)
SELECT ACCOUNTS_SEQ.nextval, '이름' || LEVEL, 10000
FROM dual 
CONNECT BY LEVEL <= 1000000;

ALTER SEQUENCE accounts_seq MAXVALUE 99999999;

SELECT COUNT(*) FROM ACCOUNTS a ;
DELETE FROM ACCOUNTS a2 ;
SELECT * FROM ACCOUNTS a WHERE ACCOUNT_NAME = '이름956999';

DROP INDEX IDX_NAME;
